baseURL: 'https://songyangyu.com/'
languageCode: 'en-us'
title: "Yangyu's Notes"
theme: "ananke"

Paginate: 20

permalinks:
  # TODO: translate .html suffix to the ones without it
  posts: "/posts/:slug"

# it's default to `en` anyway
defaultContentLanguage: en
languages:
  en:
    languageName: "English"
    # name: "English"
    title: "Yangyu's Notes"
    contentDir: "content/english"
    weight: 1

    menu:
      main:
        - identifier: about
          name: About
          pre: <i class='fa fa-heart'></i>
          url: /about/
          weight: 110

  zh:
    title: "洋宇的笔记"
    weight: 2
    contentDir: "content/chinese"
    languageName: "中文"

    params:
      mainSections:
      - posts
      - book-reviews

googleAnalytics: G-57BKLXW3P2
disqusShortname: songyangyu

sectionPagesMenu: main

# defined by ananke. Ref: https://github.com/theNewDynamic/gohugo-theme-ananke
params:
  author: Yangyu
  show_reading_time: true
  ananke_socials:
  - name: twitter
    url: https://twitter.com/songyangyu
  - name: github
    url: https://github.com/flyfy1
  - name: linkedin
    url: https://www.linkedin.com/in/yangyu-song-25895120/
  
  recent_posts_number: 10
  date_format: "2006-01-02"