// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var ReactDOMTextComponent, instantiateReactComponent;
    console.log('runned');
    ReactDOMTextComponent = (function() {
      function ReactDOMTextComponent(text) {
        this._currentElement = '' + text;
        this._rootNodeID = null;
      }

      ReactDOMTextComponent.prototype.mountComponent = function(rootID) {
        this._rootNodeID = rootID;
        return '<span data-reactid="' + rootID + '">' + this._currentElement + '</span>';
      };

      return ReactDOMTextComponent;

    })();
    instantiateReactComponent = function(node) {
      if (typeof node === 'string' || typeof node === 'number') {
        return new ReactDOMTextComponent(node);
      } else {
        return null;
      }
    };
    return window.React = {
      render: function(ele, container) {
        var componentInstance, markup;
        componentInstance = instantiateReactComponent(ele);
        markup = componentInstance.mountComponent(React.nextReactRootIndex++);
        return container.innerHTML = markup;
      }
    };
  })();

}).call(this);
